import Head from 'next/head'
import Navbar from '../components/Navbar'

export default function Home() {
  return (
    <div>
      <Head>
        <title>NextGen CMS Platform</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar/>

      <main>
        <h1>UNDER DEVELOPMENT</h1>
      </main>

      <footer>
        <a>© NextGen Solutions</a>
      </footer>
    </div>
  )
}
