import Head from 'next/head'
import NavbarPr from '../components/NavbarPr'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>NextGen CMS Platform</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <NavbarPr/>

      <main className="text-2xl space-x-4 text-center my-10">
        <h1>UNDER DEVELOPMENT</h1>
      </main>

      <footer className={styles.footer}>
        <a>© NextGen Solutions</a>
      </footer>
    </div>
  )
}
