import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>NextGen CMS Platform</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>UNDER DEVELOPMENT</h1>
      </main>

      <footer className={styles.footer}>
        <a>© NextGen Solutions</a>
      </footer>
    </div>
  )
}
